---
title: Netlify Test
timezone: UTC
collections:
  menus:
    title: Menus
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/netlify-test/"
theme: jekyll-theme-merlot
